// <auto-generated />
namespace CoreBankingApplication.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class assignTill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assignTill));
        
        string IMigrationMetadata.Id
        {
            get { return "201809121010392_assignTill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
