// <auto-generated />
namespace CoreBankingApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addglcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addglcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201808151659359_Addglcategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
